apiVersion: v1
kind: Service
metadata:
  name: nginx-external-service
  namespace: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    


# kubectl apply -f nginx-external-service.yaml
# kubectl get svc -n nginx
# you can search by Inside cluster → http://nginx-external-service

  #  Outside cluster → http://<EXTERNAL-IP>

  # node port is also external service , je tu oh bnoni a fr tenu type:loadbalancer ni likhna but target ports  de badlikhna nodePort:30007 , then you can access it via publicIP:30007