apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-rep-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

# kubectl get replicaset -n nginx
# kubectl apply -f replicaset.yml
# kubectl scale replicaset nginx-replicaset -n nginx --replicas=3
# kubectl get pods -n nginx  -o wide  (you see pods are assigning to which node) 
# kubectl delete -f replicaset.yml
